### PR TITLE
Add authors to blog posts

### LINKED ISSUE #5: Add real authors to blog posts (e.g. for Atom/RSS)
_From @schuster on May 4, 2016 15:4_

Blocked on https://github.com/greghendershott/frog/issues/162

_Copied from original issue: nuprl/nuprl.github.io#34_

### PR DESCRIPTION
**Pull request by mhyee**
Templates are updated to show blog authors. Blog posts now need to specify author metadata, otherwise the author will show up as "PRL."

One inconvenience is that "new blog post" template does not contain the Authors field; [this is something that needs to be fixed in Frog](https://github.com/greghendershott/frog/blob/master/frog/private/new-post.rkt#L58L60). So we need to do it manually.

Screenshot of the blog index.
image

Screenshots of blog posts.
image

Closes #5

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Lgtm. Thank a lot!

**Comment by LeifAndersen** [comment]
Cool, merging.

**Comment by maxsnew** [comment]
Hey, this broke a link on my website.

**Comment by mhyee** [comment]
Thanks for the catch. Looks like the problem is that old author URLs were in the form `blog/tags/by-author-name.html` but now it's `blog/tags/Author-author-name.html`.

The "best" fix is to probably create a bunch of auto-redirects, like [this one](https://github.com/nuprl/website/blob/master/blog/2017/05/26/racket-6-9-and-windows-10-creative-update/index.html).

I'm working on this right now.

**Comment by maxsnew** [comment]
I already changed the link. But yea not nice to break links out there. I think the best fix was to just leave the old author tags and stop using them for new posts.

**Comment by mhyee** [comment]
Fixed in https://github.com/nuprl/website/commit/9b5846ace6122c3e6940fd34f62682537f1f50db

Yeah, leaving the old posts alone was probably the smarter choice... on the other hand, using the new style going forward would have split some posts between `by-author-name.html` and `Author-author-name.html`...

**Pull request merged**
