### PR TITLE
UDLS website first commit

### PR DESCRIPTION
**Pull request by CAHollenbeck**
Request to pull UDLS website.

### CODE REVIEW

**Comment by bennn** [comment]
You should have push access now, so merge whenever.

Though, since this website isn't really part of the PRL, maybe you want to make a `neu-udls.github.io` website instead?

**Comment by LeifAndersen** [comment]
I agree with Ben. Is there any reason you're using this repo rather than a different one? (Especially since there are no links to the prl website on the page, or any links from the prl website to this one.)

**Comment by CAHollenbeck** [comment]
Jan, what do you think?

**Comment by CAHollenbeck** [comment]
I am happy with anything that works for you. I don’t see any problem with having additional stuff on the PRL web site. I personally don’t like creating new things. 

Jan Vitek, Professor 
Computer Science, 
Northeastern University

**Comment by bennn** [comment]
If you make a new website:
- Josh can have push access
- it'll be easier to transfer ownership to new organizers
- nobody will complain if the site isn't written in Racket

**Comment by ulysses4ever** [comment]
My 5c is that it feels more like a separate site.

**Comment by gasche** [comment]
No opinion on where the webpage should go (I think it's fine either way), but I just wanted to say that this sounds like a really nice idea. Thanks for organizing it!

**Comment by mfelleisen** [comment]
I would prefer for the PRL web site to focus on PRL things.

**Comment by CAHollenbeck** [comment]
Okay, it's going into a new site.

**Pull request closed without merging**
