### PR TITLE
[Blog Post] Bridging the System Configuration Gap

### PR DESCRIPTION
**Pull request by aatxe**
cc @gasche 

The post is actually on my blog with this serving as a cross-post link, but I'd appreciate any feedback:
https://aaronweiss.us/posts/2017-06-05-bridging-the-system-configuration-gap.html

You can comment [here](https://github.com/aatxe/aaronweiss.us/commit/6dc4b6df0ee1d686c088b9ff1fad286bbf37e803) if you like inline comments.

### CODE REVIEW

**Comment by bennn** [comment]
Let's merge & post to social media on Thursday/Friday ?

**Comment by aatxe** [comment]
Thanks for the feedback, @bennn! :)

**Comment by aatxe** [comment]
@gasche The date has been updated now.

**Comment by gasche** [comment]
Thanks! (Feel free to merge yourself when you feel there is consensus, that's our standard for blog posts to let authors do last-minute changes if they feel like it.)

**Comment by aatxe** [comment]
I think I'm actually unable to.

**Pull request merged**
