### PR TITLE
Optimized images to save bandwidth (with some quality loss).

### PR DESCRIPTION
**Pull request by aatxe**
Attempting to browse the site with poor Internet made it very apparent how beastly bandwidth usage is (especially the People page). I went and used imagemagick to optimize all of the images for better bandwidth usage. There is nominally quality loss, but at least to my taste, very little of it is perceptible. The most noticeably different appears to be Clinger (and it's probably because of the color sampling settings I used). Overall, it saves 7 MB of Bandwidth (extra important since our cache settings are horrendous, and the images expire from browser caches after just 10 minutes). As a percentage, I believe this should be around 85%.

For posterity, the settings used with imagemagick were (excluding resize which was used for people photos too):
```
-sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB
```

### CODE REVIEW

**Comment by gasche** [comment]
The quality is fine, feel free to merge.

**Comment by aatxe** [comment]
I still don't have permission to do that. :)

**Comment by bennn** [comment]
@aatxe you should be able to merge now

**Comment by LeifAndersen** [comment]
It would make sense to have it run the imagemagik command as part of the build process, otherwise we'd have to run it every time someone uploads a new picture.

(Obviously we would have the originals to run imagemagik on, so we're not making a copy of a copy of a...

**Pull request merged**
