### PR TITLE
rework contacts page: several columns, no ugly narrow paragraphs

### PR DESCRIPTION
**Pull request by ulysses4ever**
This tries to address #4. See the pictures there.

### CODE REVIEW

**Comment by mhyee** [comment]
I like the new look.

In response to @bennn, is it really harder to maintain? I suppose adding/removing roles will need some more fiddling, but how often does that happen?

I haven't looked at CSS in ages, so I'm not sure what the best way of doing a grid is.

**Comment by ulysses4ever** [comment]
@mhyee @bennn thanks for looking into it! 

@bennn Currently, I don't think there is an easy way to remove `row`s because of irregular sizes of the 'cells', both horizontal and vertical. Otoh, br/br I don't like very much too. I think someone with more experience in CSS could improve that later. Thus far, I think, this is a progress on the current miserable outlook of the page. I would go one step at a time.

**Comment by ulysses4ever** [comment]
Basically, I tried to leave one-giant-row as it was before, in the first place. But it looked bad. That's why I introduced explicit rows. I don't think they make maintaing much harder. Not for swapping the names. For adding/deleting roles -- maybe a bit harder. That is the price you have to pay for a nice looking page instead of lets-put-everything-in-a-column page.

**Comment by ulysses4ever** [comment]
@bennn I think I addressed both of your concerns now: replaced br's with a style, and removed explicit rows. Surprisingly, the latter didn't break the flow and the result is seemingly the same. Are you good with the result yet?

**Comment by bennn** [comment]
This is better, yes. (PS feel free to merge things like this anyway --- I'll use the "changes requested" button if something's really surprising to me)

**Comment by ulysses4ever** [comment]
Thanks, Ben!

**Pull request merged**
