### PR TITLE
Seminar date is a link to the seminar anchor.

### PR DESCRIPTION
**Pull request by mhyee**
Also remove dead JS scroll code. (It animated the scrolling, put an offset (to play nicely with a fixed header, which we don't have), and then erased the anchor from the browser URL.)

Here's what it looks like.
screen shot 2016-12-20 at 17 13 22

For collapsed seminars, it's still a link, but the colour is grey.

The motivation is so that I can easily get the link to tweet, instead of digging around the source code (which I can't do from a phone, which is relevant because you can't sign into two accounts on desktop Twitter but you can on mobile Twitter).

### CODE REVIEW

**Comment by gasche** [comment]
Instead of linkifying the date, which is a bit heavy visually, could you add an "anchor" icon to the left (or right) of the title? I'm thinking of the anchor that is already used on the frontpage:

```html
<a href="http://www.ccs.neu.edu/"><span class="glyphicon glyphicon-link"></span></a>
```

(the frontpage code also had some horrendous `style` inline which I got rid of.)

**Comment by mhyee** [comment]
Yeah, that was my original idea, but usually the date is used as a permalink.

Anyway, here's a quick mockup.

Expanded:
screen shot 2016-12-20 at 17 31 44

Collapsed:
screen shot 2016-12-20 at 17 32 04

**Comment by mhyee** [comment]
And here's what it really looks like, in blue/grey.

Expanded:
screen shot 2016-12-20 at 18 58 33

Collapsed:
screen shot 2016-12-20 at 18 58 42

**Comment by gasche** [comment]
I still have a mild preference for "left of the title" but I think that this is just fine. It looks good. Thanks for the work.

**Pull request merged**
