### PR TITLE
blog: add comment from Mitch

### PR DESCRIPTION
**Pull request by bennn**
Mitch sent me a nice comment that I'd like to add to the blog post.

This "comment section" looks like this when built:

screen shot 2018-12-03 at 16 53 08

Looks okay?

### CODE REVIEW

**Comment by howell** [comment]
Looks good to me, but is there a way for "You wrote:" to include Mitch's name?

**Comment by bennn** [comment]
It sounds like you're thinking the "you" is about Mitch. But, Mitch sent me an email that started with "Hi Ben, You wrote ....", so I'm the "you".

How about I delete this first line, and have the comment start with the "The best solution ...." quote?

**Comment by mhyee** [comment]
You could just delete the "You wrote" bit. It works especially well in this case because Mitch is quoting the last line.

Nitpick, feel free to ignore: The current format looks like there will be more comments. Unless/until we implement comments (#98), it might be better to make it look like a "one-off comment." For example, add a little comment like "Addendum: Mitch Wand sent me the following comment" and put the entire thing in a quote.

**Comment by howell** [comment]
Oh, I see now. Yes, I think what you propose would have been clearer to me.

**Comment by bennn** [comment]
Updated:

screen shot 2018-12-03 at 17 21 33

**Pull request merged**
