### PR TITLE
blog: PRL offsite

### PR DESCRIPTION
**Pull request by bennn**
Records and retrospectives on the PRL offsite

More comments for the "Looking Back" section are welcome

### CODE REVIEW

**Comment by howell** [comment]
thanks for writing this up

**Comment by mhyee** [comment]
Thanks for the writeup, this is really good!

There were some comments in the markdown, will you be leaving those into the published version, or will you take them out?

For the "Looking Back" section, I like the content, but the section (and entire post) end a bit abruptly. The lessons there also feel like specific and "low level" details, rather than a holistic retrospective. As a suggestion, maybe rename "Looking Back" to something like "Lessons Learned", and then create a new "Looking Back" section with more holistic lessons?

For example:

- What was it like organizing this event?
- What did you learn from this?
- Would you do it again, or recommend others to organize an offsite?
- Did you (and the other lab members) get what you wanted out of the offsite?
- Would you advocate for another offsite next year?
- etc.

**Comment by bennn** [comment]
> There were some comments in the markdown, will you be leaving those into the published version, or will you take them out?

I'm planning to leave those in. They're internal notes.

Ideally they shouldn't be public at all (and should be more detailed), but I don't know where else to put notes like that where we can find them again.

> For the "Looking Back" section, I like the content, but the section (and entire post) end a bit abruptly. The lessons there also feel like specific and "low level" details, rather than a holistic retrospective. As a suggestion, [....]

Ok! At first, I was hoping this pull request would attract "looking back" opinions from participants, but now I prefer your suggestion of finishing this "by the organizers" post with "by the organizers" feedback. Will do.

**Comment by bennn** [comment]
added a new ending @olekgierczak

**Comment by olekgierczak** [comment]
New ending looks good to me, and captures my retrospective feelings as well. Thanks again!

**Comment by mhyee** [comment]
I like it, thanks!

**Pull request merged**
