### PR TITLE
fabianm seminar info

### PR DESCRIPTION
**Pull request by bennn**
Official abstract coming later this week, I'll push this when it arrives.

cc @janvitek @schuster

### CODE REVIEW

**Comment by bennn** [comment]
https://github.com/nuprl/website/commit/49ccf26ea267d9676dc661e9e09a345ee57cd62a

**Comment by schuster** [comment]
The date is wrong: should be 28 November 2017.

**Comment by bennn** [comment]
Fixed, thanks
(it's Dec 5th not Nov 28)

https://github.com/nuprl/website/commit/e9aae35b67317b5aa62b5c3948ffabb16a5c91f2

**Comment by schuster** [comment]
Oops, you're right, thanks. I somehow got it into my head that the seminar was today, not next Tuesday.

**Pull request closed without merging**
