### PR TITLE
add Karl to former faculty

### PR DESCRIPTION
**Pull request by julbinb**
I am not sure when he left PRL. If anybody knows this, please, fix the year.

### CODE REVIEW

**Comment by mfelleisen** [comment]
Pls. Karl is still in his office and you never ever call someone former when he's still around :-)

**Comment by ulysses4ever** [comment]
@mfelleisen would it make sense then to put Karl on the list of current faculty?

**Comment by mfelleisen** [comment]
He would feel honored.

**Comment by julbinb** [comment]
> He would feel honored.

I am not sure what to make of this :)

Because Karl is not on the website and is working on ML now but did work on PL, we thought it would make sense to at least add him to the list of former members.

**Comment by mfelleisen** [comment]
That's not how human nature works. Especially not in Karl's case :-)

**Pull request closed without merging**
