### PR TITLE
[blog] template for Rob's teaser

### PR DESCRIPTION
**Pull request by bennn**
Dear @robertkleffner ,

Please post a comment here with markdown text, I'll put the text in the blog post, send you a preview, and then we can merge this!!!!!!

### CODE REVIEW

**Comment by robertkleffner** [comment]
Stack-based languages occupy a niche in today's programming language environment. The predominant stack-based language in use by programmers is Forth, and is found mostly on embedded devices. These languages also find use as compile targets for more popular languages: the CIL and JVM are both stack-based. Less popular but highly interesting languages to mention include [http://www.kevinalbrecht.com/code/joy-mirror/joy.html](Joy) and [http://factorcode.org/](Factor), known for their emphasis on higher-order stack-based programming.

The majority of stack-based languages are not statically typed, and it would be a stretch to call Forth even dynamically typed. As such, developing large projects in Forth or Factor can require great discipline on the part of the programmer to avoid type errors.

In this talk, I presented the development of type inference for stack-based languages as a linear sequence, divided into two overarching segments:

- An algebraic system known as *stack effects*
- Systems that can be encoded as *nested pairs* in standard functional programming languages

The thread of research on stack effects began with Jaanus Pöial in the early 1990's, and is a formalization of a commenting style well-known in the Forth community. The nested tuple systems were first examined by Okasaki in 1993 in the context of Haskell, and were later applied to higher-order stack-based languages. At the end, I give some avenues for extending the research on these systems, and list some pitfalls to be avoided in further research.

**links here I'm assuming**

**Comment by bennn** [comment]
Added the content. Let me know if you want to make changes, and I'll wait until we have the link to merge.

Also. Do you want "Rob" or "Robert"?

**Comment by robertkleffner** [comment]
I pushed the changes and set up the pull request. I don't have any changes
I want to make to the post, so fire away.

Rob is fine, and tends to be what I prefer.

Thank you!

**Comment by bennn** [comment]
merged! https://github.com/nuprl/website/commit/7d646848af8df596cde36aa9a2d1850c2eedf410

**Comment by gasche** [comment]
Could we have a link to the PDF that does not bring us to github's horrible internal PDF-viewer implementation? I don't remember whether that is possible with github-hosted PDFs; then we could also upload the current PDF version to the blog and serve it statically from there -- people would have a much nicer viewing experience thi sway, I believe.

**Comment by mhyee** [comment]
I think the two alternatives are 1) serve the PDF from the website, or 2) use a service like [RawGit](http://rawgit.com/). RawGit explicitly notes that it's a free service with absolutely no guarantees.

From the [RawGit FAQs](https://github.com/rgrove/rawgit/blob/master/FAQ.md#why-is-this-necessary-cant-i-just-load-files-from-github-directly), it seems to be impossible (by design) to properly serve a PDF from a Git repo.

**Comment by gasche** [comment]
I vote for serving the PDF.

**Comment by gasche** [comment]
PR proposed: #61.

**Comment by gasche** [comment]
@robertkleffner, I got some comments on reddit that you may be interested in:

- on [r/ocaml](https://www.reddit.com/r/ocaml/comments/5yukrx/type_inference_in_stackbased_programming_languages/)
- on [r/haskell](https://www.reddit.com/r/haskell/comments/5yukuo/type_inference_in_stackbased_programming_languages/)

**Comment by bennn** [comment]
@robertkleffner (before I forget), the code in the Okasaki section needs more newlines

**Pull request closed without merging**
