### PR TITLE
Small pointer blog post re History of Actors

### PR DESCRIPTION
**Pull request by tonyg**
Reasonable post? Anything else I should include? Did I do everything format- and repo-layout-wise right?

### CODE REVIEW

**Comment by gasche** [comment]
I would add a link to [the course webpage](http://www.seas.harvard.edu/courses/cs252/2016fa/) for people curious about what else could be discussed there.

**Comment by gasche** [comment]
@benn can we add Tony to the PRL group for commit rights?

**Comment by bennn** [comment]
I am bennn with 3 n's.

And yes

**Comment by tonyg** [comment]
@gasche Good point re: link to the class; I added a bit of description too. Better?

**Comment by gasche** [comment]
Better, and merged. (I question giving a link to a PDF to describe a class, but that was not your choice.)

Thanks!

**Pull request merged**
