### PR TITLE
blog: add cross-post proving a toy compiler correct

### PR DESCRIPTION
**Pull request by dbp**
I wrote a blog post about proving a (very) toy compiler correct, based on a conversation William and I had with a person at POPL. This is a cross-post, but the post on my site is not public yet (insofar as anything can be not public on the internet), so feedback / edits / suggestions are all welcome (from anyone, but particularly curious what @bennn @wilbowma @maxsnew and @gasche if he's still lurking around think). Not planning on posting it anywhere before on the PRL blog. The link, for the lazy, is: https://dbp.io/essays/2018-01-16-how-to-prove-a-compiler-correct.html

### CODE REVIEW

**Comment by gasche** [comment]
I think that the post is very nice. One additional thing you could do is link to content that goes above what you have shown. For example, [Xavier Leroy's OPLSS lectures](https://xavierleroy.org/courses/Eugene-2012/) show correctness of compilation for a language with not only arithmetic expressions, but also control-flow instructions.

On the other hand, I think that `hs-to-coq` is not as interesting an idea that you make it sound in your post (I don't really agree with the way you present it). There are two ways to "translate" a programming language into Coq to verify program. The easy way, which is to take a small subset that can be easily shoved into Coq, and the hard way, which is to design a way to express in Coq the semantics of the full language (or at least an interesting, non-total subset of it). 

Easy translations are simple to implement, it mostly a matter of implementing the guard condition for the recursive functions of your language. (I have seen prototypes in OCaml and Scala I think). But they are a dead end:

1. The subset of the language supported is very limited, making practical use unrealistic.
2. The hard translation is *not* an extension of the easy translation (the types change, etc.), meaning that if you decide to move to the hard translation (to prove real programs) you have to throw away the work you performed under the easy translation.
3. The easy translation is fundamentally wrong: you believe that you are proving things about Haskell program, but this is incorrect, you are proving things about Coq programs that have a similar syntax but different semantics (disregarding infinite values, etc.). You can prove properties in Coq that do not hold of the Haskell program. In practice that does not make easy-translations useless for increasing assurance in your code (you will still catch bugs in the process), but it severely weakens your guarantees -- you cannot state anything formally until you have used the hard translation tool.

The result of proving a program using an easy translation is no different from first translating the code to Coq, throwing away the original version, and then writing proofs about the Coq version. You could just write Coq code in the first place.

(Coq (or Agda, etc.) may not be as convenient a language to use for syntactic reasons, but then I think that investing effort in improving those languages is worthwhile -- for example, `fun 'pattern => e` is available since Coq 8.6, and that makes a nice usability difference.)

For an example of a "hard translation" tool, see Arthur Charguéraud's [CFML](http://www.chargueraud.org/softs/cfml/).

**Comment by wilbowma** [comment]
@gasche, I think your criticism ignores the context. While `hs-to-coq` might not be solving the hard PL problem, the goal here is mostly (I think, based on context) to introduce compiler correctness to a relative non-expert audience. (Annie is working in ML). For that, a tool like `hs-to-coq` is very valuable exactly because it solves the easy problem in a good way.

**Comment by wilbowma** [comment]
@dbp:

In order to importance:
- Under "Formalizing", I found the side note very confusing. For one, the difference between the new `compile` and old `compile` was subtle, and the old one was off the screen. For two, that side note takes up almost an entire section, except for the first paragraph; I got confused about what "formalizing" even referred to, and went back on forth on that section a few times.
- For the more expert readers, worth ending with some of the caveats @gasche points out about this method of proving a Haskell-implemented compiler correct, how much more complicated things get when you move to separate compilation.
- Bit wordy. E.g. "Give a more concrete sense of what exactly you need to show when you are proving a compiler correct. " could be "Give a concrete example of proving compiler correctness."
- might be worth linking to "what even is compiler correctness" when under "Proving Things"

**Comment by dbp** [comment]
@gasche Thanks for the pointer to Xavier's OPLSS lectures -- I'll definitely link to them! 

Re: the more substantive critique. You are right, of course -- there is a fundamental limitation to this "easy" approach, and there are mismatches that they completely gloss over (like, saying inductive types in Coq are the same as Haskell data types!).

But I think from an engineering perspective, it's actually an incredibly useful idea, and your comment that "it is no different from first translating and then throwing away the original" gets at that point. If I have an existing program that mostly _could_ have been written with Coq (or Agda), but it wasn't, and I want to verify it, having a tool that automatically translates it (and doing refactorings in the original language to get it the last bit to "could have been written with Coq") is incredibly valuable, even if I then throw out the original.

If I _don't_ throw out the original, an interesting question is: say I took the Coq version as ground truth and extracted to Haskell, using that as the executable. How different is that from taking the original as the executable? In both cases what I am running doesn't line up with what I proved correct! But I think the actual code on both ends would probably look pretty similar! 

I don't see this `hs-to-coq` tool as ever being useful for translating most or even much of Haskell. What I do see it as useful is allowing someone to essentially write Gallina in Haskell, which I think has practical engineering (if not particularly interesting theoretical) uses. It's funny, when I saw the talk at CPP, I had a similar reaction to what you write (I was mostly struck by its limitations), but when William and I were talking with Annie it seemed incredibly relevant -- as she has an existing compiler written in Haskell, and this way she could continue to have it work as an executable as she refactors it to line up well enough with Gallina to have `hs-to-coq` work (at which point maybe she would throw out the haskell and rely on extraction, or maybe she wouldn't).

**Comment by dbp** [comment]
@wilbowma 

Good point re: linking to your blog post. I was wondering about linking to it, but wasn't sure where. 

I think you're right about the first point. Truthfully, I wrote the function wrong the first time, and got the error mentioned, did the refactoring, and then realized that I had written the wrong function. But it seemed important to point out that things that are "obviously recursive and terminating" in Haskell will very often not be when translated, hence adding the (awkward) digression. Maybe I should actually just change the whole problem to compute a sequence of arithmetic instructions? Then it won't be a digression at all, and there won't be multiple versions...

And yeah, I can add some more caveats, and maybe be more explicit about the audience (which you read accurately -- non-experts, at least in terms of PL, verification: people who may have implemented compilers, but aren't sure what it means to prove them correct).

**Comment by dbp** [comment]
I incorporated most of the feedback -- moved the digression into an addendum (I tried making it be the central result, but it made things more complicated in ways that weren't particularly illuminating), and added another addendum containing Gabriel's criticism, with a forward reference at the beginning. I also made a explicit note about the intended audience. I didn't really do anything about William's comment about writing: not because I don't agree, but I don't want to spend much more time on it! I may make another pass on it tonight or tomorrow though...

Anyone else have any feedback, or should I publish?

**Comment by wilbowma** [comment]
On Thu, Jan 18, 2018 at 01:11:33PM -0800, Daniel Patterson wrote:
> I didn't really do anything about William's comment about writing: not because I don't agree, but I
> don't want to spend much more time on it!
Totally legit; unpolished but published information is more useful than polished and unpublished.
My polishing habits has prevented me from publishing a few blog posts.

**Comment by bennn** [comment]
I'll read all this tonight. No need to wait for me.

**Comment by dbp** [comment]
@mhyee Do I ping you to twitter this up? :)

**Comment by mhyee** [comment]
I was going to do this later this afternoon, but if you want to make it easier, tweet on your own and I'll retweet. :)

**Comment by maxsnew** [comment]
Sorry for the post-post reply.
Why does the `eval` function for the stack machine succeed when there's more than one thing left on the stack? Wouldn't it be a better correctness theorem if the first case was `eval [n] [] = Right n`, or better yet, just have the `eval` function produce the final (possibly stuck state) and then in the correctness theorem say `eval (compile x) = ([eval' x], [])`?

**Comment by dbp** [comment]
@maxsnew There's no particularly good reason to not require a single element on the final stack... As it stands, the stack language allows you to do useless computation (i.e., compute stuff but then push it onto the stack and never use it again), which would be prevented if you required the stack to have only one element. Is this a good thing? I don't know... To your other point, again, I don't have a good reason to do it the way I did it (except maybe a slight bias towards using `Either` for results when writing Haskell).

**Pull request merged**
