### PR TITLE
Add Getting Started in PL post

### PR DESCRIPTION
**Pull request by schuster**
I'd like to start cross-posting some of the posts from my personal blog on the PRL blog. This PR just adds a post that links to my own blog, but I'd like to get feedback on how others think cross-posting to the lab blog should work.

### CODE REVIEW

**Comment by gasche** [comment]
I'm strongly in favor of cross-posting in principle -- the lab blog can and should serve as a "planet" where those of our personal posts that are relevant to the lab get aggregated together. On the details I'm willing to go for whatever each author feels more comfortable with.

I see roughly three families of approaches:

- Re-post the same content in full, with a one-line header/footer "this post originally appeared on my personal blog". This is a common practice, see for example [julia bloggers](http://www.juliabloggers.com/) or, in reverse, Bruce Schneier's [originally appeared as an essay in (this journal)](https://www.schneier.com/blog/archives/2016/11/hacking_and_the.html) posts.

- Have a short summary of the content (enough to let readers decide whether they want to read through) written by the author of the post (possibly just a quotation of the introduction of the post). 

- Just have a link.

I think that which of those solutions we choose depends on the preference of each of us, and also on the cost/effort involved -- if your own blog is not in a Markdown format in the first place, re-posting the same content is going to require a painful transition and we don't want to do that.

**Comment by bennn** [comment]
I like "just the link" for this post. (Your personal blog looks very nice.)

But I have a strong preference that a "just-the-link" cross post doesn't have its own page. Clicking the title should go straight to the link, if possible.

**Comment by bennn** [comment]
Ah, it's super easy to link the title of a blog post to somewhere else. Here's a simple post that does it:

```
    Title: [test](https://www.google.com)
    Date: 2016-11-29T21:24:03
    Tags: test

_Replace this with your post text. Add one or more comma-separated
Tags above. The special tag `DRAFT` will prevent the post from being
published._

<!-- more -->
```

**Comment by mhyee** [comment]
> But I have a strong preference that a "just-the-link" cross post doesn't have its own page. Clicking the title should go straight to the link, if possible.

I agree with this. As a reader, I don't like it when I click a link, expecting a blog post, and then have to click another link. A short summary---or just the first paragraph as an introduction---helps a lot. (As a reader, I'd prefer a full repost, but as a blogger, I understand the difficulty in porting over to Markdown and then having to maintain two versions of the same post.)

Also, a slightly unrelated gripe: when blog posts are finally merged and published, the publication date is the date the PR was opened. For example, the SRC post was published a few days ago, but the date is from a few weeks ago. Does this bother anyone else? Is the only solution to rename the blog post and manually update the date?

**Comment by schuster** [comment]
Thanks for the feedback. I like the idea that it's up to the author to decide what works for them.

There's another downside to republishing the entire post on a different site: the comment conversation is split across sites (although it looks like Frog doesn't support comments, at least on our blog). Admittedly, this will already happen with sites like Twitter, Reddit, Hacker News, etc., but it might still be worth avoiding even more split conversations.

I'd like to come up with a convention for marking link-only cross-posts so the reader knows they're going to a new site. I was thinking just adding "(Cross-Post)" at the end of the title, e.g. "Getting Started in Programming Languages (Cross-Post)". Thoughts?

**Comment by schuster** [comment]
@mhyee Yes, the date issue bothers me, and I don't know any better solution. For my own posts, though, I don't mind manually renaming it if that's what has to be done.

**Comment by gasche** [comment]
I don't think we need to rename the file (I think the date is only there to avoid conflicts?), just the "Date" field in the post metadata.

**Comment by schuster** [comment]
Doesn't the filename also dictate the URL?

**Comment by gasche** [comment]
It does, but I would still expect the posts to be sorted by data metadata, not this part. We could probably fork Frog to remove the reliance of the date in (filename, URL, rendering output directory), and just suppose we won't have name conflicts between different posts.

**Comment by schuster** [comment]
Forking frog seems like a heavy-handed approach, and I could see that approach breaking oddly down the line.

This seems like another choice where the author should be able to do as they wish - they can either do the work to rename the file, or just ignore it and publish with a slightly off date.

**Comment by mhyee** [comment]
I think it's OK if the URL doesn't match the publication date. People don't really look at URLs (especially when they're long), and in many publications (e.g. NYT), it's not uncommon for the URL and article title to mismatch. (It's especially amusing if the title needs to be changed because of controversy or a factual error, but then the URL isn't changed.)

So let the author decide to rename the file or not, and ask everybody to update the date before merging?

**Comment by gasche** [comment]
Yes. (Forking frog, or using a different blog generator, may still ultimately be necessary because it is frustratingly inappropriate on several fronts (eg. the multi-author support thing is also a big problem).)

**Comment by takikawa** [comment]
Instead of forking frog, it may be helpful to contribute a patch upstream that lets you update the date with a command. It shouldn't be too hard to implement.

**Comment by schuster** [comment]
Okay, well my post is good enough for now, so I'm merging it, but we can still discuss the other issues here.

**Comment by gasche** [comment]
We may want to refine slightly over this solution because the [syndication feed](http://prl.ccs.neu.edu/blog/feeds/all.atom.xml) item produced is not optimal: cliking it goes to our blog, precisely to [this page with just the title](http://prl.ccs.neu.edu/blog/2016/11/30/-getting-started-in-programming-languages-cross-post-http-jschuster-org-blog-2016-11-29-getting-started-in-programming-languages/), and then you have to click the title again to go to the actual content. It would be best of course if we could have the URL of the feed item (`<link rel="alternate">`in Atom parlance) point to the original post directly (again, changes to Frog are required with explicit cross-posting support), but otherwise it would be nice if we had a link to the original post in the article's header, because people could then follow it from their syndication feed (so one extra click instead of two to access the content).

**Pull request merged**
