### PR TITLE
elect a Twitter Tycoon

### PR DESCRIPTION
**Pull request by gasche**

### CODE REVIEW

**Comment by mhyee** [comment]
Alternative title: Twitter Tsar.

**Comment by gasche** [comment]
Updated.

**Comment by bennn** [comment]
Can you provide a description for "Twitter Tycoon"? What is the bare minimum a person in this position should do?

(Maybe we can get Spencer Florence -- a former undergrad here, now with Robby at Northwestern -- to do the job, since he's already the Twitter person for Racket.)

**Comment by bennn** [comment]
Description: tweet about the blog posts! and anything else important

**Pull request merged**
