### PR TITLE
Add fix to make races when deploying much less likely.

### PR DESCRIPTION
**Pull request by dbp**
@gasche @bennn 

Here's the quick fix I suggested. See the commit for description, but it matches our email thread.

I have _not_ tested this on Travis -- it's somewhat of a pain to test (I did test the shell conditional syntax locally), so as long as it looks good to y'all, we should just push it and if it doesn't work I'll fix it (i.e., test it live!).

I looked into submitting the issue if things go wrong, but it didn't look trivial (there is a gem `ghi` that allows you to do this, but you need to authenticate, and it doesn't seem like it'll use the same `.netrc` that we use for authenticating with git).

### CODE REVIEW

**Comment by gasche** [comment]
It looks good to me. Is there a return code that the deploy script could use to get some failure notification on the PR?

**Comment by dbp** [comment]
Probably `exit 1` will travis things went wrong. I'll add that.

**Comment by bennn** [comment]
Cool, let's live-test.

**Comment by dbp** [comment]
Well, I didn't make it _stop_ deploying :) 

Still remains to be seen if this actually catches a race (which we could simulate by adding a commit that adds an artificial delay in the build, then committing a reversal to that -- the first build should take a long time, and should abort rather than overwriting the second commit).

**Pull request merged**
