### PR TITLE
Updates seminars for Cogumbreiro talk

### PR DESCRIPTION
**Pull request by GouwarPower**

### CODE REVIEW

**Comment by CosineP** [comment]
Happy to stare at diffs for 30 seconds and also check that the build goes up alright.   But I believe Ming-Ho said it's fine to commit directly for this sort of change if you'd rather.

**Comment by CosineP** [comment]
Of course right after saying that I actually have a comment, @GouwarPower:   looks like the space between @p and the {braces} in the bio results in the braces getting rendered literally.

**Comment by GouwarPower** [comment]
I'll push a fix directly. Thanks!

**Comment by ulysses4ever** [comment]
I think it's a bad idea to commit anything more than typo fixes directly to master. But that's a personal preference which I have no time to argue for, so do as you like. Just wanted to voice this…

**Comment by mhyee** [comment]
The middle ground, then, is to merge the PR immediately after opening it. This sends a notification out to people who are subscribed, and lets people comment afterwards if there are issues.

I think it's a bit redundant, since the seminar announcement is already going to be sent out. But having the PR for comments could be useful.

I don't feel too strongly about which method you end up choosing.

**Comment by ulysses4ever** [comment]
Yes, opening a PR and merging right away is a good strategy, and it's how it's been for long time I believe.

**Pull request merged**
